export default {

    GENERATE_TOKEN: "/api/tokenGenrate/jwtToken",
    USER_SIGN_IN: "/api/userAuth/userSignin",
    USER_SIGN_UP: "/api/userAuth/userSignup",
    SIGN_UP_OTP: "/api/userAuth/userVerify",
    RESEND_OTP: "/api/userAuth/resentOTP",
    FORGOT_PASSWORD: "/api/userAuth/forgotPassword",
    NEW_PASSWORD_UPDATE: "/api/userAuth/newPasswordUpdate",
    EDIT_USER_PROFILE: "/api/userAuth/editUserProfile",
    GET_COUNTRY_LIST: "/api/userAuth/getCountryList",
    GET_USER_PROFILE: "/api/userAuth/getUserProfile",
    USER_PAYMENT: "/api/payment/userPayment",
    VERIFY_USER:"/api/userAuth/userVerifybySms",
    
    DASHBOARD: "/api/dashboard/getDashboardListData",
    GET_MOVIE_DETAIL: "/api/movie/getMovieDetail",
    MOVIELIST: "/api/movie/getMovieList",
    TV_SERIAL_LIST: "/api/tvshow/serialList",
    NEWS_LIST: "/api/news/getNewsList",
    SERIALDETAIL: "/api/tvshow/getSerialDetail",
    NEWSDETAIL: "/api/news/getnewsDetail",
    SERIAL_EPISODE: "/api/tvshow/getSerialEpisode",
    SERIAL_SEASON: "/api/tvshow/getSerialSeason",
    GET_PACKAGE_PLAN: "/api/payment/getPackagePlan",
    USER_MOVIE_LIKE: "/api/webservice/userMoviesLike",
    GET_WATCH_LIKED_MOVIE: "/api/webservice/get_watchLikeMovies",
    DASHBOARD_SEARCHING: '/api/dashboard/dashboardSearching',
    COUPON_CODE: "/api/payment/applyCoupon",
    SERIAL_LIST: "/api/tvshow/getCategorySerialListbycategory",
    MOVIE_REVIEW: "/api/movie/moviesReview",
    CONTINUE_WATCHING_DATA: "/api/movie/continueWatchingMovie",
    CONTINUE_WATCHING_TV_DATA: "/api/tvshow/continueWatchingserial",
    SEASON_SERIAL_EPISODE:"/api/tvshow/getSerialEpisode",
    EPISODE_DETAILS:"/api/tvshow/getSerialEpisodeDetail",
    CREATESUBSCRIPTIONMOBILE:"/api/payment/createsubcriptionmobile",
    CREATETRANSACTION:"/api/payment/checktransaction",
    CANCELSUBSCRIPTION:"/api/payment/cancelsubscription",
}